AEG/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from AEG import settings
admin.autodiscover()
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
	#url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('app_auth.urls', namespace='auth')),
	url(r'^', include('app_classes.urls', namespace='classes')),
	url(r'^', include('app_essays.urls', namespace='essays')),	
	#url(r'^', include('app_registration.urls', namespace='register')),
  	url(r'^accounts/', include('app_registration.backends.default.urls')),
)

urlpatterns += staticfiles_urlpatterns()

if not settings.DEBUG:
	urlpatterns += patterns('',
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

app_auth/urls.py
from django.conf.urls import patterns, url
from app_auth import views

urlpatterns = patterns('',
	#url(r'^$', views.user_login, name='user_login'),
	url(r'^$', views.LoginView.as_view(), name='user_login'),
	url(r'^logout$', views.user_logout, name='user_logout'),
	url(r'^dashboard/$', views.dashboard, name='dashboard'),
	url(r'^profile/$', views.profile_view, name='profile'),
	url(r'^help/$', views.help,  name='help'),
	url(r'^settings/profile/$', views.profile_edit, name='edit_profile'),
	url(r'^settings/account/$', views.password_edit, name='edit_password'),
	url(r'^settings/grading-system/$', views.grading_system, name='gradesys'),
	url(r'^settings/grading-system/new$', views.grading_system_new, name='gradesys_new'),
	url(r'^settings/grading-system/(?P<gradeSys_id>\d+)/$', views.grading_system_view, name='grades'),
	url(r'^settings/grading-system/delete/$', views.grading_system_delete, name='gradesys_delete'),

)

app_classes/urls.py
from django.conf.urls import patterns, url
from app_classes import views

urlpatterns = patterns('',
	url(r'^dashboard/$', views.dashboard, name='dashboard'),
	url(r'^classes/$', views.class_teacher, name='classes'),
	url(r'^classes/add/$', views.teacher_addNewClass, name='add'),
	url(r'^classes/submit/$', views.submit, name='submitClass'),
	url(r'^classes/(?P<class_id>\d+)/edit/$', views.edit, name='edit'),
	url(r'^classes/enroll/$', views.enroll, name='enroll'),
	url(r'^classes/(?P<class_id>\d+)/viewClass/$', views.viewClassList, name='viewClass'),
	# ex: /polls/5/vote/
    url(r'^classes/delete/$', views.delete, name='delete'),
    url(r'^classes/removeStudent/$', views.removeStudent, name='removeStudent'),
    url(r'^classes/inviteStudent/$', views.inviteStudent, name='inviteStudent'),
)

app_essays/urls.py
from django.conf.urls import patterns, url
from app_essays import views

urlpatterns = patterns('',
	url(r'^essays/new/$', views.new_essay, name='new'),
	url(r'^essays/$', views.list_essay, name='list'),
	url(r'^essays/(?P<essay_id>\d+)/$', views.exam_details, name='details'),
	url(r'^essays/answer/(?P<essay_response_id>\d+)/$', views.answer_essay, name='answer'),
	url(r'^essays/submissions/(?P<essay_response_id>\d+)/$', views.essay_submission, name='submission'),
	url(r'^essays/time_remaining/(?P<essay_response_id>\d+)/$', views.time_remaining_ajax, name='time_remaining'),
)

templates/base/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
		<link href="{% static 'base/css/bootstrap.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'base/css/bootstrap-responsive.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'base/css/flat-ui.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'base/css/style.css' %}" rel="stylesheet" media="screen">
  		<link rel="shortcut icon" type="text/css" href="{% static 'base/img/icons/favicon.ico' %}" />
		
		<script src="http://code.jquery.com/jquery-1.9.1.js"></script>

		{% block custom_style %}{% endblock %}

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="../../assets/js/html5shiv.js"></script>
			<script src="../../assets/js/respond.min.js"></script>
		<![endif]-->
	</head>

	<body>
		{% include "base/header.html" %}
		<div class="row-fluid">
			<div class="span3">
				{% include "base/sidebar.html" %}
			</div>
			<div class="span9">
				{% block content %}{% endblock content %}
			</div>
		</div>
		<!--script src="{% static 'base/js/jquery.js' %}"></script-->
		<!--script src="{% static 'base/js/jquery-1.8.3.min.js' %}"></script-->
		
		<script src="{% static 'base/js/bootstrap.min.js' %}"></script>
		<script src="{% static 'base/js/bootstrap-select.js' %}"></script>
		<script src="{% static 'base/js/bootstrap-switch.js' %}"></script>
		<script src="{% static 'base/js/flatui-checkbox.js' %}"></script>
		<script src="{% static 'base/js/flatui-radio.js' %}"></script>
		<script src="{% static 'base/js/html5shiv.js' %}"></script>
		<script src="{% static 'base/js/bootstrap-tooltip.js' %}"></script>
		<script src="{% static 'base/js/bootstrap-transition.js' %}"></script>
		<script src="{% static 'base/js/jquery.tagsinput.js' %}"}></script>
		<script src="{% static 'base/js/jquery.placeholder.js' %}"}></script>
		<script src="{% static 'base/js/application.js' %}"}></script>

		{% block custom_script %}{% endblock %}
	</body>
</html>

templates/base/base_error.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
		<link href="{% static 'base/css/bootstrap.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'base/css/bootstrap-responsive.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'base/css/flat-ui.css' %}" rel="stylesheet" media="screen">
  		
  		<style>
 			.center {text-align: center; height: 100%}
 			.error-message {margin: 0px 200px}
		</style>

		{% block custom_style %}{% endblock %}

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="../../assets/js/html5shiv.js"></script>
			<script src="../../assets/js/respond.min.js"></script>
		<![endif]-->
	</head>

	<body>
		{% block content %}{% endblock content %}
	</body>
</html>

templates/base/base_login.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
		<link href="{% static 'base/css/bootstrap.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'base/css/bootstrap-responsive.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'base/css/flat-ui.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'base/css/style.css' %}" rel="stylesheet" media="screen">
  		<link rel="shortcut icon" type="text/css" href="{% static 'base/img/icons/favicon.ico' %}" />
		{% block custom_style %}
		{% endblock %}

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="../../assets/js/html5shiv.js' %}"></script>
			<script src="../../assets/js/respond.min.js' %}"></script>
		<![endif]-->
	</head>

	<body>
		{% if user.is_authenticated %}
			{% block content %}{% endblock content %}
		{% else %}
			{% block login %}{% endblock login %}
		{% endif %}
	</body>

	<script src="{% static 'base/js/jquery.js' %}"></script>
	<script src="{% static 'base/js/bootstrap.js' %}"></script>
	<script src="{% static 'base/js/flatui-checkbox.js' %}"></script>
	<script src="{% static 'base/js/jquery-1.8.3.min.js' %}"></script>
	<script src="{% static 'base/js/flatui-checkbox.js' %}"></script>

</html>

templates/base/base_profile.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
		<link href="{% static 'base/css/bootstrap.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'base/css/bootstrap-responsive.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'base/css/flat-ui.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'base/css/style.css' %}" rel="stylesheet" media="screen">
  		<link rel="shortcut icon" type="text/css" href="{% static 'base/img/icons/favicon.ico' %}" />
		
		<script src="http://code.jquery.com/jquery-1.9.1.js"></script>

		{% block custom_style %}{% endblock %}

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="../../assets/js/html5shiv.js"></script>
			<script src="../../assets/js/respond.min.js"></script>
		<![endif]-->
	</head>

	<body>
		{% include "base/header.html" %}
		<div class="page-content">
			<div class="content">
			{% block content %}{% endblock content %}
			</div>
		</div>

		{% block custom_script %}{% endblock %}
	</body>
</html>

templates/base/base_register.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
		<link href="{% static 'base/css/bootstrap.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'base/css/bootstrap-responsive.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'base/css/flat-ui.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'base/css/style.css' %}" rel="stylesheet" media="screen">
  		<link rel="shortcut icon" type="text/css" href="{% static 'base/img/icons/favicon.ico' %}" />
		{% block custom_style %}{% endblock %}

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="../../assets/js/html5shiv.js' %}"></script>
			<script src="../../assets/js/respond.min.js' %}"></script>
		<![endif]-->
	</head>

	<body>

	<div class="login">
		<div class="login-screen">	
		{% block register %}{% endblock register %}		
  		</div>
	</div>
	</body>

	<script src="{% static 'base/js/jquery.js' %}"></script>
	<script src="{% static 'base/js/bootstrap.js' %}"></script>
	<script src="{% static 'base/js/flatui-checkbox.js' %}"></script>
	<script src="{% static 'base/js/jquery-1.8.3.min.js' %}"></script>
	<script src="{% static 'base/js/flatui-checkbox.js' %}"></script>

</html>

templates/base/base_register_form.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
		<link href="{% static 'base/css/bootstrap.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'base/css/bootstrap-responsive.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'base/css/flat-ui.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'base/css/style.css' %}" rel="stylesheet" media="screen">
  		<link rel="shortcut icon" type="text/css" href="{% static 'base/img/icons/favicon.ico' %}" />
		{% block custom_style %}{% endblock %}

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="../../assets/js/html5shiv.js' %}"></script>
			<script src="../../assets/js/respond.min.js' %}"></script>
		<![endif]-->
	</head>

	<body>

	<div class="signup">
		<div class="signup-screen">	
		{% block register %}{% endblock register %}		
  		</div>
	</div>
	</body>

	<script src="{% static 'base/js/jquery.js' %}"></script>
	<script src="{% static 'base/js/bootstrap.js' %}"></script>
	<script src="{% static 'base/js/flatui-checkbox.js' %}"></script>
	<script src="{% static 'base/js/jquery-1.8.3.min.js' %}"></script>
	<script src="{% static 'base/js/flatui-checkbox.js' %}"></script>

</html>

templates/base/base_settings.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
		<link href="{% static 'base/css/bootstrap.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'base/css/bootstrap-responsive.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'base/css/flat-ui.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'base/css/style.css' %}" rel="stylesheet" media="screen">
  		<link rel="shortcut icon" type="text/css" href="{% static 'base/img/icons/favicon.ico' %}" />
  		<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
		{% block custom_style %}{% endblock %}

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="../../assets/js/html5shiv.js"></script>
			<script src="../../assets/js/respond.min.js"}></script>
		<![endif]-->
	</head>

	<body>
		{% include "base/header.html" %}
		<div class="row-fluid">
			<div class="span3">
				{% include "base/sidebar_settings.html" %}
			</div>
			<div class="span9">
				{% block content %}{% endblock content %}
			</div>
		</div>

		
	    <script src="{% static 'base/js/jquery.ui.touch-punch.min.js' %}"}></script>
		<script src="{% static 'base/js/bootstrap.min.js' %}"}></script>
		{% block custom_script %}{% endblock %}

	</body>
</html>

templates/base/header.html
{% load staticfiles %}

<div class="navbar navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target="#nav-collapse-01"></button>
			<div class="nav-collapse collapse" id="nav-collapse-01">
				<a class="brand" href="{% url 'classes:dashboard' %}">
					<img class="brand-logo" src="{% static 'base/img/icons/paper_pencil.png' %}" /> TECS: Test Essay Content Software 
				</a>
				<ul class="nav pull-right">
					<li>
						<a href="/help/">Help</a>
					</li>
					<li class="active dropdown">
						<a href="#" class="dropdown-toggle"><img class="avatar" src="{{ MEDIA_URL }}{{ avatar }}" />
							{{ user.first_name }} {{ user.last_name }}
							<b class="caret"></b>
						</a>
						<ul>
							<li><a href="{% url 'auth:profile' %}">My Profile</a></li>
							<li><a href="{% url 'auth:edit_profile' %}">Settings</a></li>
							<li><a href="{% url 'auth:user_logout' %}">Logout</a></li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>

templates/base/sidebar.html
<div class="sidebar">
	<ul>
		<li {% if not active_nav or active_nav == 'DASHBOARD' %} class="active" {% endif %} >
			<a href="{% url 'classes:dashboard' %}">
				<div class="sidebar-icon fui-chat"></div>
				<div class="sidebar-content">DASHBOARD</div>
			</a>
		</li>

		<li {% if active_nav == 'CLASSES' %} class="active" {% endif %} >
			<a href="{% url 'classes:classes' %}">
				<div class="sidebar-icon fui-list"></div>
				<div class="sidebar-content">CLASSES</div>
			</a>
		</li>

		<li {% if active_nav == 'EXAMS' %} class="active" {% endif %} >
			<a href="{% url 'essays:list' %}">
				<div class="sidebar-icon fui-new"></div>
				<div class="sidebar-content">EXAMS</div>
			</a>
		</li>
	</ul>
</div>

templates/base/sidebar_settings.html
{% load staticfiles %}

<div class="todo mll mrl">
	<div class="todo-search">
		<img class="sidebar-icons" src="{% static 'base/img/icons/Settings.png' %}"><h2>Settings</h2>
	</div>
	<ul>
		<li {% if active_nav == 'PROFILE' %} class="todo-done" {% endif %}>
			<a href="{% url 'auth:edit_profile' %}" class="sidebar-link">
				<div class="todo-icon fui-user"></div>
				<div class="todo-content">
					<h4 class="todo-name">
						<strong>Profile</strong>
					</h4>
				</div>
			</a>
		</li>
		<li {% if active_nav == 'ACCOUNT' %} class="todo-done" {% endif %}>
			<a href="{% url 'auth:edit_password' %}" class="sidebar-link">
				<div class="todo-icon fui-gear"></div>
				<div class="todo-content">
					<h4 class="todo-name">
						<strong>Account</strong>
					</h4>
				</div>
			</a>
		</li>
		{% if role == 'TEACHER' %}
		<li {% if active_nav == 'GRADESYS' %} class="todo-done" {% endif %}>
			<a href="{% url 'auth:gradesys' %}" class="sidebar-link">
				<div class="todo-icon fui-check"></div>
				<div class="todo-content">
					<h4 class="todo-name">
						<strong>Grading System</strong>
					</h4>
				</div>
			</a>
		</li>
		{% endif %}
	</ul>
</div>