AEG/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from AEG import settings
admin.autodiscover()
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
	#url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('app_auth.urls', namespace='auth')),
	url(r'^', include('app_classes.urls', namespace='classes')),
	url(r'^', include('app_essays.urls', namespace='essays')),	
	#url(r'^', include('app_registration.urls', namespace='register')),
  	url(r'^accounts/', include('app_registration.backends.default.urls')),
)

urlpatterns += staticfiles_urlpatterns()

if not settings.DEBUG:
	urlpatterns += patterns('',
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

app_classes/urls.py
from django.conf.urls import patterns, url
from app_classes import views

urlpatterns = patterns('',
	url(r'^dashboard/$', views.dashboard, name='dashboard'),
	url(r'^classes/$', views.class_teacher, name='classes'),
	url(r'^classes/add/$', views.teacher_addNewClass, name='add'),
	url(r'^classes/submit/$', views.submit, name='submitClass'),
	url(r'^classes/(?P<class_id>\d+)/edit/$', views.edit, name='edit'),
	url(r'^classes/enroll/$', views.enroll, name='enroll'),
	url(r'^classes/(?P<class_id>\d+)/viewClass/$', views.viewClassList, name='viewClass'),
	# ex: /polls/5/vote/
    url(r'^classes/delete/$', views.delete, name='delete'),
    url(r'^classes/removeStudent/$', views.removeStudent, name='removeStudent'),
    url(r'^classes/inviteStudent/$', views.inviteStudent, name='inviteStudent'),
)

app_classes/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
from app_auth.models import School, Student, Teacher
from django.forms.widgets import TextInput, Select, SelectMultiple, Textarea
from datetime import datetime

class Class(models.Model):
	school = models.ForeignKey(School)
	year_level = models.CharField(max_length=2)
	section = models.CharField(max_length=30)
	subject = models.CharField(max_length=30)
	academic_year = models.CharField(max_length=20)
	teacher = models.ForeignKey(Teacher)
	student = models.ManyToManyField(Student)
	key = models.CharField(max_length=32)
	date_created = models.DateTimeField(default=datetime.now)
	is_active = models.IntegerField(default=0)

	def __str__(self):
		return u'%s-%s %s' % (self.year_level, self.section, self.subject)

class ClassForm(ModelForm):
	class Meta:
		model = Class
		exclude = ('teacher', 'key', 'date_created', 'is_active', 'student')
		widgets = {
          'school': Select(attrs={'class':'select span12', 'data-size':10, 'data-container':"body", 'data-options':"is_hover", 'style':'position: relative' }),
          'year_level': TextInput(attrs={'class':'input-xlarge span11', 'data-name':'year_level' }),
          'section': TextInput(attrs={'class':'input-xlarge span11', 'data-name':'section'}),
          'subject': TextInput(attrs={'class':'input-xlarge span11'}),
          'academic_year': TextInput(attrs={'class':'input-xlarge span11', 'data-name':'academic_year'}),
        }

        def cleaned_Emails(self):
        	data = self.cleaned_data.get('Emails', [])
        	return data.split(',')

class EditForm(ModelForm):
	class Meta:
		model = Class
		exclude = ('teacher', 'key', 'date_created', 'is_active', 'student')
		widgets = {
			'school': Select(attrs={'class':'select span12', 'data-size':10, 'data-container':"body" }),
			'year_level': TextInput(attrs={'class':'input-xlarge span4', 'data-name':'year_level' }),
			'section': TextInput(attrs={'class':'input-xlarge span4', 'data-name':'section'}),
			'subject': TextInput(attrs={'class':'input-xlarge span4', 'data-name':'subject'}),
			'academic_year': TextInput(attrs={'class':'input-xlarge span4', 'data-name':'academic_year'}),
		}

class EnrollForm(ModelForm):
	class Meta:
		model = Class
		fields = ['school', 'key']
		widgets = {
			'school': Select(attrs={'class':'select span12', 'data-size':10, 'data-container':"body", 'data-options':"is_hover" }),
			'key': TextInput(attrs={'class':'input-xlarge span2', 'data-name':'key'}),
		}

app_classes/forms.py
from django import forms
import re
from django.core.validators import validate_email

class MultiEmailField(forms.Field):
    def to_python(self, value):
        "Normalize data to a list of strings."

        # Return an empty list if no input was given.
        if not value:
            return []
        return re.split(',\s+', value)

    def validate(self, value):
        "Check if value consists only of valid emails."

        # Use the parent's handling of required fields, etc.
        super(MultiEmailField, self).validate(value)

        for email in value:
            validate_email(email)

class MailForm(forms.Form):
	emails = MultiEmailField(label="Email", required=False, widget=forms.Textarea(attrs={'class':'span3'}))

	def cleaned_emails(self):
		data = self.cleaned_data.get('emails', [])
		return data.split(',')

class MailForm2(forms.Form):
    emails = MultiEmailField(label="Email", required=True, widget=forms.Textarea(attrs={'class':'span3'}))

    def cleaned_emails(self):
        data = self.cleaned_data.get('emails', [])
        return data.split(',')

app_classes/views.py

import os
import hashlib
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from app_classes.models import Class, ClassForm, EditForm, EnrollForm
from django.shortcuts import render, get_object_or_404
from app_auth.models import UserProfile, Teacher, School, Student
from django.db.models import Count
from django import forms
from django.forms.widgets import Textarea
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django.template.loader import render_to_string, get_template
from django.template import Context
from .forms import MailForm, MailForm2
from email.MIMEImage import MIMEImage

@login_required(redirect_field_name='', login_url='/')
def dashboard(request):
	User_Profile = UserProfile.objects.filter(user_id = request.user.id)
	if not User_Profile.exists():
		return redirect("/profile")
	avatar = User_Profile.get(user_id=request.user.id).avatar
	
	return render(request, 'app_classes/dashboard2.html', {'avatar':avatar, 'active_nav':'DASHBOARD'})
		
@login_required(redirect_field_name='', login_url='/')
def class_teacher(request, err=None, success=None, formStud=None):
	User_Profile = UserProfile.objects.filter(user_id = request.user.id)
	if not User_Profile.exists():
		return redirect("/profile")

	User_Profile = User_Profile.get(user_id=request.user.id)
	teacher = Teacher.objects.filter(user=request.user)
	hasClasses = None
	power = True
	formEnroll = formStud or EnrollForm()
	link = 'app_classes/class_teacher.html'
	if teacher.exists():
		sections = Class.objects.filter(teacher=teacher)
	else:
		student = Student.objects.filter(user=request.user)
		if student.exists():
			link = 'app_classes/viewClasses.html'
			sections = Class.objects.filter(student=student)
		else:
			sections = None
			power = False
			hasClasses = 'You have no permission to add Classes.'
	if power and (sections is None or not sections.exists()):
		hasClasses = 'You don\'t have Classes yet'
	avatar = User_Profile.avatar
	return render(request, link, {'avatar':avatar, 'active_nav':'CLASSES', 'formEnroll':formEnroll, 'sections':sections, 'error': err, 'success':success, 'hasClasses':hasClasses, 'power':power})

@login_required(redirect_field_name='', login_url='/')
def teacher_addNewClass(request, add_form=None, email_form=None):
	avatar = UserProfile.objects.get(user_id = request.user.id).avatar
	addClass_form = add_form or ClassForm()
	teacher = Teacher.objects.filter(user=request.user)
	name = Class.objects.filter(teacher=teacher)
	formMails = email_form or MailForm()
	return render(request, 'app_classes/teacher_addNewClass.html', 
			{'addClassForm' : addClass_form, 'formMails':formMails,'next_url': '/classes', 'avatar':avatar, 'active_nav':'CLASSES', 'name':name})

@login_required(redirect_field_name='', login_url='/')
def submit(request):
	if request.method == "POST":
		form_class = ClassForm(data=request.POST)
		formMails = MailForm(data=request.POST)
		success_url = request.POST.get("next_url", "/")

		if form_class.is_valid() and formMails.is_valid():
			forms = form_class.cleaned_data
			school_info = forms['school']
			subject_info = forms['subject']
			yearType_info = forms['year_level']
			section_info = forms['section']
			academicYear_info = forms['academic_year']

			emails = formMails.cleaned_data
			mail = []
			for email in emails.values():
				mail = email

			#rendered = render_to_string("users/emails/data.txt", {'data': data})
			try:
				teacher = Teacher.objects.get(user=request.user)
			except Teacher.DoesNotExist:
				return class_teacher(request, 'You don\'t have permission to add Classes.')

			class_info = Class.objects.filter(school=school_info).filter(section=section_info).filter(subject=subject_info).filter(teacher=teacher).filter(year_level=yearType_info).filter(academic_year=academicYear_info)
			if class_info.exists():
				return class_teacher(request, 'That Class already exists.')

			form = form_class.save(commit=False)
			form.teacher = teacher
			form.date_created = timezone.now()
			form.is_active = True

			random_data = os.urandom(128)
			random_data = hashlib.md5(random_data).hexdigest()[:16]
			form.key = random_data
			form.save()

			template = get_template('app_classes/perl.html').render(
				Context({
					'sender': request.user,
					'studentList': form,
				})
			)
			if mail:
				fp = open('./static/base/img/icons/Mail@2x.png', 'rb')
				msgImage = MIMEImage(fp.read())
				fp.close()

				msgImage.add_header('Content-ID', '<image1>')

				mailSend = EmailMessage('[TECS] Invitation to join Class', template, 'fsvaeg@gmail.com', mail )
				mailSend.content_subtype = "html"  # Main content is now text/html
				mailSend.attach(msgImage)
				mailSend.send()
			#send_mail('Subject', 'You are invited to class '+ yearType_info + '-' + section_info + ' ' + subject_info + '. The key class is: ' + random_data, 'fsvaeg@gmail.com', mail)
			
			return redirect(success_url)
		else:
			return teacher_addNewClass(request, form_class, formMails)


@login_required(redirect_field_name='', login_url='/')
def edit(request, class_id):
	class_info = get_object_or_404(Class, pk=class_id)
	power = False
	if request.method == "POST":
		formEdit = EditForm(data=request.POST)
		power = True
		if formEdit.is_valid():
			temp = formEdit.cleaned_data
			class_info.school = temp['school']
			class_info.year_level = temp['year_level']
			class_info.section = temp['section']
			class_info.subject = temp['subject']
			class_info.academic_year = temp['academic_year']
			class_info.save()
			return viewClassList(request, class_id, 'Changes to class details were saved.')

	if not power:
		formEdit = EditForm(initial={'school':class_info.school, 'year_level':class_info.year_level, 'section':class_info.section, 'academic_year':class_info.academic_year, 'subject':class_info.subject})
	avatar = UserProfile.objects.get(user_id = request.user.id).avatar
	return render(request, 'app_classes/teacher_editClass.html', {'avatar':avatar, 'active_nav':'CLASSES', 'class_info':class_info, 'formEdit':formEdit})
			
@login_required(redirect_field_name='', login_url='/')
def delete(request):
	class_info = get_object_or_404(Class, pk=request.POST['class_id'])
	class_info.delete()
	return class_teacher(request, 0, 'You successfully deleted a class.')

@login_required(redirect_field_name='', login_url='/')
def viewClassList(request, class_id, message=None, success=True):
	class_info = get_object_or_404(Class, pk=class_id)
	avatar = UserProfile.objects.get(user_id = request.user.id).avatar
	formMails = MailForm2()
	return render(request, 'app_classes/viewClassList.html', {'mailSend':False, 'studentList':class_info, 'active_nav':'CLASSES', 'avatar':avatar, 'succ': success,'success':message, 'formMails': formMails})

@login_required(redirect_field_name='', login_url='/')
def enroll(request):
	avatar = UserProfile.objects.get(user_id = request.user.id).avatar
	err = None
	if request.method == "POST":
		formEnroll = EnrollForm(data=request.POST)
		if formEnroll.is_valid():
			temp = formEnroll.cleaned_data
			key = temp['key']
			school = School.objects.filter(name=temp['school'])
			class_info = Class.objects.filter(school=school).filter(key=key)
			if class_info.exists():
				student = Student.objects.get(user=request.user)
				class_info = class_info.get(key=key)
				class_info.student.add(student)
				return class_teacher(request, 0, 'You are added to the class.')
			err = 'Invalid Key Combination.'
		else:
			err = 'There is unfilled form field.'
	else:
		formEnroll = EnrollForm()
	return class_teacher(request, err, 0, formEnroll)

@login_required(redirect_field_name='', login_url='/')
def removeStudent(request):
	class_info = get_object_or_404(Class, pk=request.POST['class_id'])
	student = get_object_or_404(Student, pk=request.POST['student_id'])
	class_info.student.remove(student)
	return viewClassList(request, request.POST['class_id'], 'You successfully removed a student.')

@login_required(redirect_field_name='', login_url='/')
def inviteStudent(request):
	class_id = request.POST['cid']
	class_info = get_object_or_404(Class, pk=class_id)
	sender = request.user
	avatar = UserProfile.objects.get(user_id = request.user.id).avatar
	message = 'Invalid Email address(es)'
	success = False
	mail = None
	count = 0

	if request.method == "POST":
		formMails = MailForm2(data=request.POST)
		sendNow = request.POST.get('sendNow')

		template = get_template('app_classes/perl.html').render(
			Context({
				'sender': sender,
				'studentList': class_info,
			})
		)
		if formMails.is_valid():
			emails = formMails.cleaned_data
			mail = []
			for email in emails.values():
				mail = email
			
			count = len(mail)
			if sendNow == 'sendNow':
				fp = open('./static/base/img/icons/Mail@2x.png', 'rb')
				msgImage = MIMEImage(fp.read())
				fp.close()

				msgImage.add_header('Content-ID', '<image1>')

				mailSend = EmailMessage('[TECS] Invitation to join Class', template, 'fsvaeg@gmail.com', mail )
				mailSend.content_subtype = "html"  # Main content is now text/html
				mailSend.attach(msgImage)
				mailSend.send()
				success = True
				message = 'Invitations were sent successfully.'
				return viewClassList(request, class_id, message, success)
		else:
			return viewClassList(request, class_id, message, success)
	else:
		formMails = MailForm2()

	#return viewClassList(request, class_id, message, success)
	return render(request, 'app_classes/viewClassList.html', {'mails':mail, 'active_nav':'CLASSES', 'count':count, 'formMails':formMails,'sender':sender,'avatar':avatar, 'studentList':class_info, 'mailSend':True})

templates/app_classes/class_teacher.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block title %}
TECS: Test Essay Checking Software | Teacher Classes
{% endblock %}

{% block content %}
<head>
	<script>
	    $(function() {
		    var tooltips = $( "[title]" ).tooltip();
		    $(document)(function() {
		    	tooltips.tooltip( "open" );
		    })
	    });
	</script>
</head>
<div class="page-content">
	<div class="row-fluid">
		<div class="content">
			{% if power %}
			<p class="pull-right">
				<a href="{% url 'classes:add' %}" data-toggle="tooltip" data-trigger="hover" data-placement="left" title data-original-title="Add New Class" class="btn btn-warning"><i class="fui-plus"></i></a>
			</p>
			{% endif %}
			<img class="title-icons" src="{% static 'base/img/icons/Clipboard@2x.png' %}">
			<h3 class="title">My Classes</h3>
			
			{% if hasClasses %}
				<div class="alert alert-block alert-error">
		          <h4><strong>Oops!</strong></h4>
		          {{ hasClasses }}
		        </div>
		    {% else %}
			{% if success %}
				<br>
				<div class="alert alert-block alert-success">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
		          <h4><strong>Success!</strong></h4> {{ success }}
		        </div>
		    {% endif %}
			{% if error %}
				<br>
				<div class="alert alert-block alert-error">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
		          <h4><strong>Warning!</strong></h4>
		          {{ error }}
		        </div>
		    {% endif %}

			<table class="table table-striped">
				<thead>
					<tr>
						<th style="width: 3px"><center>#</center></th>
						<th style="width: 53px"><center>School Name</center></th>
						<th style="width: 20px"><center>Class Name</center></th>
						<th style="width: 15px"><center>Subject Name</center></th>
						<th style="width: 3px"><center>Students</center></th>
						<th style="width: 3px"><center>View</center></th>
						<th style="width: 3px"><center>Delete</center></th>
					</tr>
				</thead>
				<tbody>
					{% for classes in sections %}
						<tr>
							<td><center>{{forloop.counter}}</center></td>
							<td><center>{{classes.school.name}}</center></td>
							<td><center>{{classes.year_level}} - {{classes.section}}</center></td>
							<td><center>{{classes.subject}}</center></td>
							<td><center>{{classes.student.all.count }}</center></td>
							<td><center><a href="{% url 'classes:viewClass' classes.id %}" class="btn btn-primary"><span class="fui-location"></span></a></center></td>
							<td><center><button type="button" class="delsys-button btn btn-danger" data-id={{ classes.id }} data-toggle="modal" data-target="#confirm-delete"><i class="fui-cross"></i></span></button></center></td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
			{% endif %}
		</div>
	</div>
</div>

<div id="confirm-delete" class="modal hide fade" data-backdrop="static">
	<div class="modal-header palette-alizarin">
		<h3 class="text-white">Confirm Delete</h3>
	</div>
	<div class="modal-body">
		<p>Are you sure you want to delete this Class?</p>
		<p>Continuing with this action, will erase all the students who enroll in this class. </p>
		<form action="{% url 'classes:delete' %}" method="post">
			{% csrf_token %}
			<input type="hidden" id="class_id" name="class_id" value="">
		<form>
	</div>
	<div class="modal-footer">
		<button type="submit" name="gradesys-delete" class="btn btn-danger pull-left">Delete <span class="fui-cross"></span></button>
		<button class="btn btn-inverse" data-dismiss="modal" aria-hidden="true">Close</button>
	</div>
</div>

<script>
	$(".delsys-button").on("click", function() {
		var gradesys_id = $(this).data('id')
		$("#class_id").val(gradesys_id)
	});
</script>

<script src="{% static 'base/js/jquery.min.js' %}"></script>
{% endblock content %}

templates/app_classes/viewClassList.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block title %}
TECS: Test Essay Checking Software | Home
{% endblock %}

{% block content %}
<head>
	<script src="{% static 'base/js/jquery.min.js' %}"></script>

	<script>
	    $(function() {
		    var tooltips = $( "[title]" ).tooltip();
		    $(document)(function() {
		    	tooltips.tooltip( "open" );
		    })
	    });
	</script>
	
</head>

<div id="myModal" class="modal hide fade" data-backdrop="static">
	<div class="modal-header palette-emerald">
		<h3 class="text-white">Make Invitation</h3>
	</div>
	<div class="modal-body">
		<form action="{% url 'classes:inviteStudent' %}" method="post">{% csrf_token %}
		{% for form in formMails %}
		<div class="control-group">
			<div class="controls">
				<div>
					<p>Please seperate each person by comma. For example:</p>
					<div style="padding-left: 100px">
					<i>cheryleighverano@gmail.com, master@yahoo.com</i>
					</div>
				</div><br/>
				{{ form }}
				{% for error in form.errors %}
				<p class="text-error">{{ error }}</p>
				{% endfor %}
			</div>		
		</div> 	
		{% endfor %}
		<input type="hidden" id="cid" name="cid" value={{ studentList.id }} >
	</div>
	<div class="modal-footer"> 
		<button type="submit" name="gradesys-send"  class="btn btn-primary pull-left" >Make Invitation <span class="fui-check"></span></button>
		<button type="button" class="btn btn-warning" data-dismiss="modal" aria-hidden="true">Cancel <i class="fui-new"></i></button>
	</div>
	</form>
</div>	

<div class="page-content">
	<div class="row-fluid">
		<div class="content">
			<p class="pull-right">
				<a href="#myModal" role="button" data-toggle="modal" data-trigger="hover" data-placement="left" title data-original-title="Invite Students" class="btn btn-success sentMail "><i class="fui-mail"></i></a>
				<a href="{% url 'classes:edit' studentList.id %}" data-toggle="tooltip" data-trigger="hover" data-placement="left" title data-original-title="Edit Class Info" class="btn btn-warning"><i class="fui-new"></i></a>
			</p>
			<img class="title-icons" src={% static 'base/img/icons/Pocket@2x.png' %}>
			<h3 class="title">{{ studentList.year_level }}-{{ studentList.section }}: {{ studentList.subject }} for (S.Y. {{ studentList.academic_year }})</h3>
			
			{% if mailSend %}
				<div class="alert alert-block alert-success">
					Please review the invitation below carefully. You may not cancel an invitation once it has been submitted. If you want to disregard this mail, click <b>"Cancel"</b>. If you are ready to submit your invitation, click <b>"Send Invitation"</b>.
					<br/><br/>
					Number of people to Invite: <b>{{ count }}</b>
				</div>

				<form class="form form-horizontal" action="{% url 'classes:inviteStudent' %}" method="POST"> {% csrf_token %}
					<fieldset>
						<div class="palette-turquoise">
							<center>
								<img class="title-icons" style="float: none; padding-bottom:3px; padding-top:5px; margin-right: -5px" src="{% static 'base/img/icons/Mail@2x.png' %}">
			            		<div class="btn btn-primary" style="text-shadow:none"><b>You have been invited to join this class!</b></div>
			            	</center>
			         	</div>

				          <div class="demo-text-box prl" style="border-radius: 0px;">
				            <p>
				            	From: <span style="color: #1abc9c">{{ sender.email }} [{{ sender.last_name }}, {{ sender.first_name }}]</span><br/>
								Subject: Invitation to join {{ studentList.year_level }}-{{ studentList.section }}<br/>
								Class Key: <span style="color: #1abc9c">{{ studentList.key }}</span><br/><br/>
								Please <a href="tecs.herokuapp.com" style="color: #1abc9c; text-decoration: none;">Log-in</a> or Register to <a href="http://tecs.herokuapp.com/accounts/register/" style="color: #1abc9c; text-decoration: none">tecs.herokuapp.com</a> and enter the Class Key to enroll in a Class.
							</p>
							<div style="display:none">
								{% for form in formMails %}
									{{ form }}
								{% endfor %}
							</div>
				          </div>
				        <input type="hidden" id="cid" name="cid" value={{ studentList.id }} >
				        <div class="form-actions">
		    				<input type="hidden" value="sendNow" name="sendNow" />
							<button type="submit" class="btn btn-primary"><b>Send Invitation</b><i class="fui-check"></i></button> 
							<a href="{% url 'classes:viewClass' studentList.id %}" type="button" class="btn btn-danger"><b>Cancel</b><i class="fui-cross"></i></a>
						</div>
					</fieldset>
				</form>
				{% else %}

			<table class="table table-striped">
				{% if studentList.student.all.count %}
					{% if success %}
						<div {% if succ %} class="alert alert-block alert-success" {% else %} class="alert alert-block alert-error" {% endif %}>
						<button type="button" class="close" data-dismiss="alert">&times;</button>
				          <h4><strong>{% if succ %}Success!{% else %}Error!{% endif %}</strong></h4> {{ success }}
				        </div>
				    {% endif %}
				<thead>
					<tr>
						<th><center>#</center></th>
						<th><center>Last Name</center></th>
						<th><center>First name</center></th>
						<th><center>Email</center></th>
						<th><center>Status</center></th>
						<th><center>Remove</center></th>
					</tr>
				</thead>
				<tbody>
					{% for student in studentList.student.all %}
					<tr>
						<td><center>{{student.id}}</center></td>
						<td><center>{{student.user.last_name}}</center></td>
						<td><center>{{student.user.first_name}}</center></td>
						<td><center>{{student.user.email}}</center></td>
						<td>{% if student.user.is_active %}<center style="color:#1abc9c">Active</center>
						{% else %}<center style="color:red">Inactive</center></td>{% endif %} 
						<td><center><button type="button" class="delsys-button btn btn-danger" data-classid={{ studentList.id }} data-studentid={{ student.id }} data-toggle="modal" data-target="#confirm-delete"><i class="fui-cross"></i></span></button></center></td>
					</tr>	
					{% endfor %}			
				</tbody>
				{% elif not success %}
					<div class="alert alert-block alert-error">
			          <h4><strong>Oops!</strong></h4>
			          	You haven't added students yet.
			        </div>
				{% else %}
					<br>
					<div {% if succ %} class="alert alert-block alert-success" {% else %} class="alert alert-block alert-error" {% endif %}>
						<button type="button" class="close" data-dismiss="alert">&times;</button>
			          <h4><strong>{% if succ %}Success!{% else %}Error!{% endif %}</strong></h4> {{ success }}
			        </div>
			    {% endif %}
			</table>
			{% endif %}
		</div>
	</div>
</div>

<div id="confirm-delete" class="modal hide fade" data-backdrop="static">
		<div class="modal-header palette-alizarin">
			<h3 class="text-white">Confirm Delete</h3>
		</div>
		<div class="modal-body">
			<p>Are you sure you want to delete this student from the class?</p>
			<p>Continuing with this action, will erase his/her account on this class. </p>
			<form action="{% url 'classes:removeStudent' %}" method="post">{% csrf_token %}
				<input type="hidden" id="class_id" name="class_id" value="">
				<input type="hidden" id="student_id" name="student_id" value="">
			<form>
		</div>
		<div class="modal-footer">
			<button type="submit" name="gradesys-delete" class="btn btn-danger pull-left">Delete <span class="fui-cross"></span></button>
			<button class="btn btn-inverse" data-dismiss="modal" aria-hidden="true">Close</button>
		</div>
</div>

<script>
	$(".delsys-button").on("click", function() {
		var classid = $(this).data('classid')
		var studid = $(this).data('studentid')
		$("#class_id").val(classid)
		$("#student_id").val(studid)
	});
</script>

<script src="{% static 'base/js/jquery.min.js' %}"></script>

{% endblock %}