AEG/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from AEG import settings
admin.autodiscover()
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
	#url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('app_auth.urls', namespace='auth')),
	url(r'^', include('app_classes.urls', namespace='classes')),
	url(r'^', include('app_essays.urls', namespace='essays')),	
	#url(r'^', include('app_registration.urls', namespace='register')),
  	url(r'^accounts/', include('app_registration.backends.default.urls')),
)

urlpatterns += staticfiles_urlpatterns()

if not settings.DEBUG:
	urlpatterns += patterns('',
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

app_essays/urls.py
from django.conf.urls import patterns, url
from app_essays import views

urlpatterns = patterns('',
	url(r'^essays/new/$', views.new_essay, name='new'),
	url(r'^essays/$', views.list_essay, name='list'),
	url(r'^essays/(?P<essay_id>\d+)/$', views.exam_details, name='details'),
	url(r'^essays/answer/(?P<essay_response_id>\d+)/$', views.answer_essay, name='answer'),
	url(r'^essays/submissions/(?P<essay_response_id>\d+)/$', views.essay_submission, name='submission'),
	url(r'^essays/time_remaining/(?P<essay_response_id>\d+)/$', views.time_remaining_ajax, name='time_remaining'),
)

app_essays/models.py
from django.db import models
from django import forms
from django.forms import ModelForm, DateTimeInput, TextInput, Textarea, Select
from django.utils import timezone
from django.utils.timezone import utc
from django.contrib.auth.models import User
from app_auth.models import Student, Teacher
from app_classes.models import Class
import datetime, nltk.data

class GradingSystem(models.Model):
	system = models.CharField(max_length=50)
	created_by = models.ForeignKey(User)
	description = models.TextField(max_length=100, blank=True)
	is_active = models.IntegerField(default=0)
	
	def __str__(self):
		return u'%s (%s)' % (self.system, self.description)

class Grade(models.Model):
	grading_system = models.ForeignKey(GradingSystem)
	name = models.CharField(max_length=20)
	value = models.IntegerField()	
	
	def __str__(self):
		return u'%s = %s' % (self.name, self.value)

class Essay(models.Model):
	title = models.CharField(max_length=100)
	instructor = models.ForeignKey(Teacher)
	class_name = models.ForeignKey(Class)
	instructions = models.TextField()
	grading_system = models.ForeignKey(GradingSystem)	
	start_date = models.DateTimeField()
	deadline = models.DateTimeField()	
	duration_hours = models.IntegerField()
	duration_minutes = models.IntegerField()
	min_words = models.IntegerField()
	status = models.IntegerField()	#-1 - cancelled		0 - scheduled / not yet released	1 - on going	2 done/deadline
	date_created = models.DateTimeField(default=timezone.now())

	def __str__(self):
		return self.title

	def is_all_graded(self):
		return not EssayResponse.objects.filter(essay_id=self.pk, grade=None).exists()

class EssayResponse(models.Model):
	essay = models.ForeignKey(Essay)
	student = models.ForeignKey(Student)
	response = models.TextField(blank=True, default="")
	time_started = models.DateTimeField(blank=True, null=True)
	time_finished = models.DateTimeField(blank=True, null=True)
	status = models.IntegerField(default=0)	#0 - not yet started ; 1 - started / draft ; 2 - submitted
	grade = models.ForeignKey(Grade, null=True, blank=True)
	general_feedback = models.TextField(blank=True, default="")

	def __str__(self):
		return self.essay.title

	@property
	def time_remaining(self):
		essay_duration_sec = self.essay.duration_hours*60*60 + self.essay.duration_minutes*60
		if self.status != 0:
			delta = timezone.now() - self.time_started
			return essay_duration_sec - delta.seconds
		else:
			return essay_duration_sec

	@property
	def time_remaining_str(self):
		t = self.time_remaining
		hours = t/3600
		minutes = (t/60)%60
		time_str = str(hours) + ( ' hours' if hours > 1 else ' hour' ) if hours > 0 else ''
		time_str +=  str(minutes) + ( ' minutes' if minutes > 1 else ' minute' ) if minutes > 0 else ''
		return time_str

	@property
	def num_of_sentences(self):
		tokenizer = nltk.data.load('nltk:tokenizers/punkt/english.pickle')
		sentences = tokenizer.tokenize(essay_response.response)
		return count(sentences)

class EssayComment(models.Model):
	essay = models.ForeignKey(EssayResponse)
	start = models.IntegerField()
	end = models.IntegerField(blank=True)
	comment = models.CharField(max_length=250)

	def __str__(self):
		return self.comment

class EssayForm(ModelForm):
	class Meta:
		model = Essay
		exclude = ('instructor', 'status', 'date_created')
		widgets = {
			'title': TextInput(attrs={'class':'input-xlarge span4', 'autofocus':'autofocus'}),
			'instructions': Textarea(attrs={'class':'input-xlarge span4', 'rows':'4'}),
			'min_words': TextInput(attrs={'class':'span1'}),
			#'grading_system': ModelChoiceField(queryset=GradingSystem.objects.all(), empty_label=None),
			'duration_hours': TextInput(attrs={'class':'span1'}),
			'duration_minutes': TextInput(attrs={'class':'span1'}),
			'start_date': DateTimeInput(attrs={'class':'span4', 'type':'date'}),
			'deadline': DateTimeInput(attrs={'class':'span4', 'type':'date'}),
		}
	
	def clean_duration_minutes(self):
		duration_minutes = self.cleaned_data['duration_minutes']

		if duration_minutes > 59:
			raise forms.ValidationError("Please enter a number from 0 to 59.")

		return duration_minutes

	def clean_start_date(self):
		startdate = self.cleaned_data['start_date']
		
		if datetime.datetime.date(startdate) < datetime.datetime.date(timezone.now()):
			raise forms.ValidationError("This date has already passed.")
		return startdate
	
	def clean_deadline(self):
		deadline = self.data['deadline']
		startdate = self.data['start_date']

		if deadline < startdate:
			raise forms.ValidationError("Date for deadline must be later than the start date.")
		return deadline

class EssayResponseForm(ModelForm):
	class Meta:
		model = EssayResponse
		fields = ['response']
		widgets = {
			'response': Textarea(attrs={'class':'input-xlarge span4', 'rows':'10', 'spellcheck':'false'}),
		}

class EssayResponseGradeForm(ModelForm):
	class Meta:
		model = EssayResponse
		fields = ['grade', 'general_feedback']
		widgets = {
			'general_feedback': Textarea(attrs={'class':'input-xlarge span4', 'rows':'4'}),
		}


class EssayCommentForm(ModelForm):
	class Meta:
		model = EssayComment
		exclude = ['essay']
		widgets = {
			'start': TextInput(attrs={'class':'span1'}),
			'end': TextInput(attrs={'class':'span1'}),
			'comment': TextInput(attrs={'class':'span1'}),
		}
	
	def clean_start(self):
		clean_start = self.cleaned_data.get('start', None)
		
		return clean_start

	def clean_end(self):
		clean_end = self.cleaned_data.get('end', None)
		clean_start = self.cleaned_data.get('start', None)

		return clean_end

	def clean_comment(self):
		start = self.cleaned_data.get('start', None)
		comment = self.cleaned_data.get('comment', None)

		#if not start or not (comment.isspace() or  comment.strip() == ''):
		#	raise forms.ValidationError("This is required.")

		return comment

class GradeSysForm(ModelForm):
	class Meta:
		model = GradingSystem
		exclude = ('created_by', 'is_active')
		widgets = {
			'system': TextInput(attrs={'class':'input-xlarge span4', 'placeholder': 'System Name'}),
			'description' : Textarea(attrs={'class':'input-xlarge span4', 'rows':'4', 'placeholder':'Description'}),
		}

app_essays/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.utils import timezone
from django.http import HttpResponseRedirect, HttpResponse
from django.forms.formsets import formset_factory, BaseFormSet
from django.core.context_processors import csrf
from email.MIMEImage import MIMEImage
from django.template.loader import render_to_string
from django.core.mail import EmailMessage

from app_auth.models import UserProfile, Student, Teacher
from app_essays.models import Essay, EssayResponse, GradingSystem, EssayForm, EssayComment, Grade, EssayResponseForm, EssayResponseGradeForm, EssayCommentForm
from app_classes.models import Class

from datetime import datetime
import operator, pycurl, urllib, re
import nltk, json

@login_required(redirect_field_name='', login_url='/')
def new_essay(request):
	avatar = UserProfile.objects.get(user_id = request.user.id).avatar
	errors = 0;
	if request.method == 'POST':
		form = EssayForm(request.POST, request)
		form.fields['class_name'].queryset = Class.objects.filter(teacher = Teacher.objects.get(user_id = request.user.id))
		if form.is_valid():
			cd = form.cleaned_data
			data = form.save(commit=False)
			data.instructor = Teacher.objects.get(user_id = request.user.id)
			data.status = 1
			data.save()

			students = Class.objects.get(pk=Essay.objects.get(pk=data.pk).class_name.pk).student.all()

			emails = []
			for student in students:
				response = EssayResponse(essay=data, student=student)
				response.save()
				emails.append(student.user.email)

			c = {
                'user': request.user,
                'class': Class.objects.get(pk=Essay.objects.get(pk=data.pk).class_name.pk),
                'title': cd['title'],
            }

			fp = open('./static/base/img/icons/notes.png', 'rb')
			msgImage = MIMEImage(fp.read())
			fp.close()
			msgImage.add_header('Content-ID', '<image1>')

			email = render_to_string('app_essays/new_essay_email.html', c)

			mailSend = EmailMessage('[TECS] New exam has started!', email, request.user.email, emails )
			mailSend.content_subtype = "html"
			mailSend.attach(msgImage)
			mailSend.send()

			return list_essay(request, None, 'New exam has been added.')
		else :
			errors = 1
		
	else:
		form = EssayForm()
		form.fields['class_name'].queryset = Class.objects.filter(teacher = Teacher.objects.get(user_id = request.user.id))
	
	return render(request, 'app_essays/teacher_newExam.html', {'avatar':avatar, 'active_nav':'EXAMS', 'errors':errors, 'form': form})

@login_required(redirect_field_name='', login_url='/')	
def list_essay(request, errors=None, success=None):
	active_nav = "EXAMS"
	userProfile = UserProfile.objects.filter(user_id = request.user.id)
	if not userProfile.exists():
		return redirect("/profile")
	avatar = userProfile.get(user_id = request.user.id).avatar
	#IF USER IS A TEACHER
	if len(Teacher.objects.filter(user_id = request.user.id)) > 0:
		no_on_going_essays = 0
		no_past_essays = 0
		no_on_queue_essays = 0

		on_queue_essays = Essay.objects.filter(instructor_id = Teacher.objects.get(user_id = request.user.id).id, status=1).filter(start_date__gt=timezone.now())
		on_going_essays = Essay.objects.filter(instructor_id = Teacher.objects.get(user_id = request.user.id).id, status=1).filter(start_date__lte=timezone.now(), deadline__gte=timezone.now())
		past_essays = Essay.objects.filter(instructor_id = Teacher.objects.get(user_id = request.user.id).id).filter(deadline__lt=timezone.now())
		
		#MANUAL WAY TO CHANGE STATUS OF AN ESSAY IF IT'S PAST THE DEADLINE
		Essay.objects.filter(instructor_id = Teacher.objects.get(user_id = request.user.id).id).filter(deadline__lt=timezone.now()).update(status=2)


		if (len(on_queue_essays) == 0 ):
			no_on_queue_essays = 1	
		if (len(on_going_essays) == 0 ):
			no_on_going_essays = 1	
		if (len(past_essays) == 0):
			no_past_essays = 1
		return render(request, 'app_essays/teacher_viewExam.html',	{'avatar':avatar, 'active_nav':'EXAMS', 'no_on_queue_essays':no_on_queue_essays,'no_on_going_essays':no_on_going_essays, 'no_past_essays':no_past_essays, 'on_queue_essays':on_queue_essays,'on_going_essays':on_going_essays, 'past_essays':past_essays,'errors':errors, 'success':success})

	#IF USER IS A STUDENT
	elif len(Student.objects.filter(user_id = request.user.id)) > 0:
		#essays = Essay.objects.filter(instructor_id = Teacher.objects.get(user_id = request.user.id).id)
		no_on_going_essay_responses = 0
		no_past_essay_responses = 0

		#on_going_essay_responses = EssayResponse.objects.filter(~Q(status=2), student=Student.objects.get(user_id = request.user.id)).filter(essay__deadline__gte=timezone.now())
		on_going_essay_responses = EssayResponse.objects.filter(~Q(essay__status=-1), student=Student.objects.get(user_id = request.user.id)).filter(essay__start_date__lte=timezone.now(), essay__deadline__gte=timezone.now())
		past_essay_responses = EssayResponse.objects.filter(~Q(essay__status=-1), student=Student.objects.get(user_id = request.user.id)).filter(essay__deadline__lt=timezone.now())

		#MANUAL WAY TO CHANGE STATUS OF AN ESSAY IF IT'S PAST THE DEADLINE
		EssayResponse.objects.filter(essay__status__gt=-1, essay__status__lt=2, student=Student.objects.get(user_id = request.user.id)).filter(essay__deadline__lt=timezone.now()).update(status=2)

		if (len(on_going_essay_responses) == 0 ):
			no_on_going_essay_responses = 1	
		if (len(past_essay_responses) == 0):
			no_past_essay_responses = 1
		return render(request, 'app_essays/student_viewEssay.html', {'avatar':avatar, 'active_nav':'EXAMS','no_on_going_essay_responses':no_on_going_essay_responses, 'no_past_essay_responses':no_past_essay_responses, 'on_going_essay_responses':on_going_essay_responses, 'past_essay_responses':past_essay_responses, 'errors':errors, 'success':success})
		
@login_required(redirect_field_name='', login_url='/')
def exam_details(request, essay_id=None):
	active_nav = "EXAMS"
	avatar = UserProfile.objects.get(user_id = request.user.id).avatar
	essay = get_object_or_404(Essay, pk=essay_id, instructor=Teacher.objects.get(user=request.user))

	if request.method == 'POST':
		essay_id_post = request.POST.get('essay-id')
		essay = Essay.objects.get(pk=essay_id_post)
		essay.status = -1
		essay.save()
		return redirect('essays:list')
	else:
		students = Class.objects.get(pk=essay.class_name.pk).student.all()
		
		essay_responses = sorted(EssayResponse.objects.filter(essay_id=essay.pk), key=operator.attrgetter('student.user.last_name', 'student.user.first_name')) # I used this way of sorting because we cannot use order_by() for case insensitive sorting :(
		if essay.deadline >= timezone.now():
			return render(request, 'app_essays/teacher_viewExamInfo_onGoing.html', {'avatar':avatar, 'active_nav':'EXAMS', 'essay':essay, 'essay_responses':essay_responses})
		else:
			all_graded = EssayResponse.objects.filter(essay_id=essay.pk, grade=None).exists()
			return render(request, 'app_essays/teacher_viewExamInfo_forGrading.html', {'avatar':avatar, 'active_nav':'EXAMS', 'essay':essay, 'essay_responses':essay_responses, 'all_graded':all_graded})
	
@login_required(redirect_field_name='', login_url='/')
def answer_essay(request, essay_response_id):
	active_nav = "EXAMS"
	avatar = UserProfile.objects.get(user_id = request.user.id).avatar
	essay_response = get_object_or_404(EssayResponse, pk=essay_response_id, status__lt=2,student=get_object_or_404(Student, user=request.user))

	if essay_response.status == 0:
		essay_response.status = 1
		essay_response.time_started = datetime.now()
		essay_response.save()
		essay_response = EssayResponse.objects.get(pk=int(essay_response_id))


	if request.is_ajax():
		form = EssayResponseForm(request.POST, request)
		if form.is_valid():
			response_data = form.cleaned_data['response']
			essay_response.response = response_data
			essay_response.save()

			if request.POST['submission_type'] == 'DRAFT':
				data = {'message':'Saved!', 'has_errors':0}

			elif request.POST['submission_type'] == 'FINAL':
				essay_response.status = 2
				essay_response.time_finished = datetime.now()
				essay_response.save()
				data = {}
				
			else:
				print request.POST['submission_type']
				data = {'message':'Oops!', 'has_errors':1}
		else:
			data = {'message':'Oops! Something went wrong. Try again.', 'has_errors':1}
		
		return HttpResponse(json.dumps(data), content_type="application/json")

	elif request.method == 'POST':
		form = EssayResponseForm(request.POST, request)
		if form.is_valid():
			response_data = form.cleaned_data['response']
			essay_response.response = response_data
			essay_response.save()

			#if 'draft' in request.POST:
			#	return redirect('essays:answer', essay_response_id=essay_response.pk)

			if 'final' in request.POST:
				essay_response.status = 2
				essay_response.time_finished = datetime.now()
				essay_response.save()
				return redirect('essays:submission', essay_response_id=essay_response.pk)
		else :
			errors = 1
		
	else:
		form = EssayResponseForm(initial={'response':essay_response.response})
		return render(request, 'app_essays/student_answerEssay.html', {'avatar':avatar, 'active_nav':'EXAMS', 'essay_response':essay_response, 'form':form})

@login_required(redirect_field_name='', login_url='/')
def essay_submission(request, essay_response_id):
	active_nav = "EXAMS"
	avatar = UserProfile.objects.get(user_id = request.user.id).avatar
	essay_response = get_object_or_404(EssayResponse, pk=essay_response_id, status=2)
	numbered_response = ''

	if essay_response.response.isspace() or essay_response.response.strip() == '':
		has_submission = 0

	else:
		has_submission = 1
		tokenizer = nltk.data.load('nltk:tokenizers/punkt/english.pickle')

		index = 1

templates/app_essays/teacher_viewEssay.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block title %}
TECS: Test Essay Checking Software | Essay
{% endblock %}

{% block content %}

<div class="page-content">
<div class="row-fluid">
	<div class="content">
		<p class="pull-right">
			<a href="{% url 'essays:new' %}" class="btn btn-large btn-primary"><i class="icon-white icon-plus"></i> New Exam</a>
		</p>
		<img class="title-icons" src="{% static 'base/img/icons/Pensils@2x.png' %}">
		<h3>On-going Exams</h3>
		
		{% if no_essay %}
		<br><br>
		<div class="alert alert-block alert-error">
			<h4>Oops!</h4>
			You have no on-going exams.
		</div>
		
		{% else %}
		<table class="table table-striped">
			<thead>
				<tr>
					<th width="10%">Class</th>
					<th width="15%">Subject</th>
					<th width="25%">Essay</th>
					<th width="15%">Start</th>
					<th width="15%">Deadline</th>
					<th width="10%"></th>
				</tr>
			</thead>
			<tbody>
				{% for essay in essays %}
				<tr>
					<td>{{ essay.class_name.year_level }}-{{ essay.class_name.section }}</td>
					<td>{{ essay.class_name.subject }}</td>
					<td>{{ essay.title }}</td>
					<td>{{ essay.start_date }}</td>
					<td>{{ essay.deadline }}</td>
					<td><center><a href="{% url 'essays:details' essay.id %}">View</a></center></td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% endif %}
	</div>
</div>
</div>
{% endblock %}

templates/app_essays/teacher_viewEssaySubmission_Graded.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block title %}
TECS: Test Essay Checking Software | Essay
{% endblock %}
	
{% block custom_style %}
	<style type="text/css">
	   .demo-text-box{
		color: #000;
		padding: 7px;
		border:2px solid;
		border-radius:0px;
		border-color:#1abc9c;
		}
	
  </style>

{% endblock %}

{% block content %}	
<div class="page-content">
	<div class="span10">
		<div class="row-fluid">
			<div class="content">
				<img class="title-icons" src={% static 'base/img/icons/Retina-Ready@2x.png' %}>
				<h3 class="title">Review Essay Score</h3>
				<hr>
				{% if not has_submission %}
				<div class="alert alert-block alert-error">
					<h4>Oops!</h4>
					{{ essay_response.student.user.first_name }} did not sumbit an essay.
				</div>
				{% endif %}

				<div class="demo-text-box prl">
					<h4><center><strong> {{ essay_response.essay.title }} </strong></center> </h4>
					{% autoescape off %}
						<p>{{ numbered_response }}</p>
					{% endautoescape %}
				</div>
				<br>
				<div class="form-horizontal">
				 	<div class="control-group">
						<label class="control-label" for="inputfeedback"><strong>Rating</strong></label>
						<div class="controls" id= "inputfeedback">
							<span class="help-inline"><h1 class="text-error">{{ essay_response.grade }}</h1></span>
						</div>
					</div>

					<div class="control-group">
						<label class="control-label" for="inputcomments"><strong>Comments</strong></label>
						<div class="controls">								
							{% if not comments %}
							<p class="text-error">No comments were given.</p>
							{% else %}
							<table class="table table-bordered table-striped">
								<thead>
									<tr>
										<th width="15%">From <span class="palette-paragraph">Sentence no.</span> </th>
										<th width="10%">To</th>
										<th width="80%">Comment</th>
									</tr>
								</thead>
								<tbody>									
									{% for comment in comments %}
									<tr class="item">
										<td>{{ comment.start }}</td>
										<td>{{ comment.end }}</td>
										<td>{{ comment.comment }}</td>
									</tr>
									{% endfor %}																			
								</tbody>
							</table>
							{% endif %}
						</div>
					</div>

					<div class="control-group">  
						<label class="control-label" for="inputinst"><strong>General Feedback</strong></label>  
						<div class="controls">  
							<span class="help-inline">
								{% if not essay_response.general_feedback %}
									<p class="text-error">No feedback was given.</p>
								{% else %}
									{{ essay_response.general_feedback }}
								{% endif %}
							</span>
						</div>  
					</div>

					<a href="{% url 'essays:details' essay_response.essay.id %}" class="btn btn-inverse"><i class="fui-arrow-left"></i><b> Back</b></a> 
				</div>
			</div>
		</div>
	</div>
</div>

<script language="javascript">
	 function check()
	 {
	    AtD.checkCrossAJAX('preview', 
	    {
	       success : function(errorCount) 
	       {
	          if (errorCount == 0)
	          {
	             alert("No writing errors were found");
	          }
	       },

	       error : function(reason)
	       {
	          alert(reason);
	       }
	    });
	 }

</script>
<script src="{% static 'app_essays/js/dynamic_form.js' %}"></script>
{% endblock content %}

templates/app_essays/teacher_viewExam.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block title %}
TECS: Test Essay Checking Software | Essay
{% endblock %}

{% block content %}

<div class="page-content">
	<div class="row-fluid">
		<div class="content">
			<p class="pull-right">
				<a href="{% url 'essays:new' %}" class="btn btn-large btn-primary"><i class="fui-plus"></i> New Exam</a>
			</p>
			<img class="title-icons" src="{% static 'base/img/icons/Pensils@2x.png' %}">
			<h3>On-going Exams</h3>
			
			{% if no_on_going_essays %}
			<br><br>
			<div class="alert alert-block alert-error">
				<h4>Oops!</h4>
				You have no on-going exams.
			</div>
			
			{% else %}
			{% if success %}
			<br><br>
			<div class="alert alert-block alert-success">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<h4>Success!</h4>
					{{ success }}
			</div>
			{% endif %}
			<table class="table table-striped">
				<thead>
					<tr>
						<th width="10%">Class</th>
						<th width="15%">Subject</th>
						<th width="25%">Essay</th>
						<th width="15%">Start</th>
						<th width="15%">Deadline</th>
						<th width="10%"></th>
					</tr>
				</thead>
				<tbody>
					{% for essay in on_going_essays %}
					<tr>
						<td>{{ essay.class_name.year_level }}-{{ essay.class_name.section }}</td>
						<td>{{ essay.class_name.subject }}</td>
						<td>{{ essay.title }}</td>
						<td>{{ essay.start_date }}</td>
						<td>{{ essay.deadline }}</td>
						<td><center><a href="{% url 'essays:details' essay.id %}" class="btn btn-info">View</a></center></td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
			{% endif %}


			{% if not no_on_queue_essays %}
			<div class="row-fluidr">
				<img class="title-icons" src="{% static 'base/img/icons/Watches@2x.png' %}">
				<h3>Queued Exams</h3>
			</div>
			<table class="table table-striped">
				<thead>
					<tr>
						<th width="10%">Class</th>
						<th width="15%">Subject</th>
						<th width="25%">Essay</th>
						<th width="15%">Start</th>
						<th width="15%">Deadline</th>
						<th width="10%"></th>
					</tr>
				</thead>
				<tbody>
					{% for essay in on_queue_essays %}
					<tr>
						<td>{{ essay.class_name.year_level }}-{{ essay.class_name.section }}</td>
						<td>{{ essay.class_name.subject }}</td>
						<td>{{ essay.title }}</td>
						<td>{{ essay.start_date }}</td>
						<td>{{ essay.deadline }}</td>
						<td><center><a href="{% url 'essays:details' essay.id %}" class="btn btn-info">View</a></center></td>
					</tr>
					{% endfor %}
				</tbody>
			</table>

			{% endif %}

			<img class="title-icons" src="{% static 'base/img/icons/documents.png' %}">
			<h3>Past Exams</h3>
			
			{% if no_past_essays %}
			<br><br>
			<div class="alert alert-block alert-error">
				<h4>Oops!</h4>
				You have no past exams.
			</div>
			
			{% else %}
			<table class="table table-striped">
				<thead>
					<tr>
						<th width="10%">Class</th>
						<th width="12%">Subject</th>
						<th width="20%">Essay</th>
						<th width="12%">Start</th>
						<th width="12%">Deadline</th>
						<th width="15%">Remarks</th>
						<th width="9%"></th>
					</tr>
				</thead>
				<tbody>
					{% for essay in past_essays %}
					<tr>
						<td>{{ essay.class_name.year_level }}-{{ essay.class_name.section }}</td>
						<td>{{ essay.class_name.subject }}</td>
						<td>{{ essay.title }}</td>
						<td>{{ essay.start_date }}</td>
						<td>{{ essay.deadline }}</td>
						<td>
							{% if not essay.is_all_graded %}
								<p class="text-error">Needs Grading</p>
							{% endif %}
						</td>
						<td><center><a href="{% url 'essays:details' essay.id %}" class="btn btn-info">View</a></center></td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}