AEG/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from AEG import settings
admin.autodiscover()
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
	#url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('app_auth.urls', namespace='auth')),
	url(r'^', include('app_classes.urls', namespace='classes')),
	url(r'^', include('app_essays.urls', namespace='essays')),	
	#url(r'^', include('app_registration.urls', namespace='register')),
  	url(r'^accounts/', include('app_registration.backends.default.urls')),
)

urlpatterns += staticfiles_urlpatterns()

if not settings.DEBUG:
	urlpatterns += patterns('',
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

app_auth/urls.py
from django.conf.urls import patterns, url
from app_auth import views

urlpatterns = patterns('',
	#url(r'^$', views.user_login, name='user_login'),
	url(r'^$', views.LoginView.as_view(), name='user_login'),
	url(r'^logout$', views.user_logout, name='user_logout'),
	url(r'^dashboard/$', views.dashboard, name='dashboard'),
	url(r'^profile/$', views.profile_view, name='profile'),
	url(r'^help/$', views.help,  name='help'),
	url(r'^settings/profile/$', views.profile_edit, name='edit_profile'),
	url(r'^settings/account/$', views.password_edit, name='edit_password'),
	url(r'^settings/grading-system/$', views.grading_system, name='gradesys'),
	url(r'^settings/grading-system/new$', views.grading_system_new, name='gradesys_new'),
	url(r'^settings/grading-system/(?P<gradeSys_id>\d+)/$', views.grading_system_view, name='grades'),
	url(r'^settings/grading-system/delete/$', views.grading_system_delete, name='gradesys_delete'),

)

app_classes/urls.py
from django.conf.urls import patterns, url
from app_classes import views

urlpatterns = patterns('',
	url(r'^dashboard/$', views.dashboard, name='dashboard'),
	url(r'^classes/$', views.class_teacher, name='classes'),
	url(r'^classes/add/$', views.teacher_addNewClass, name='add'),
	url(r'^classes/submit/$', views.submit, name='submitClass'),
	url(r'^classes/(?P<class_id>\d+)/edit/$', views.edit, name='edit'),
	url(r'^classes/enroll/$', views.enroll, name='enroll'),
	url(r'^classes/(?P<class_id>\d+)/viewClass/$', views.viewClassList, name='viewClass'),
	# ex: /polls/5/vote/
    url(r'^classes/delete/$', views.delete, name='delete'),
    url(r'^classes/removeStudent/$', views.removeStudent, name='removeStudent'),
    url(r'^classes/inviteStudent/$', views.inviteStudent, name='inviteStudent'),
)

app_essays/urls.py
from django.conf.urls import patterns, url
from app_essays import views

urlpatterns = patterns('',
	url(r'^essays/new/$', views.new_essay, name='new'),
	url(r'^essays/$', views.list_essay, name='list'),
	url(r'^essays/(?P<essay_id>\d+)/$', views.exam_details, name='details'),
	url(r'^essays/answer/(?P<essay_response_id>\d+)/$', views.answer_essay, name='answer'),
	url(r'^essays/submissions/(?P<essay_response_id>\d+)/$', views.essay_submission, name='submission'),
	url(r'^essays/time_remaining/(?P<essay_response_id>\d+)/$', views.time_remaining_ajax, name='time_remaining'),
)

app_auth/forms.py

from django.contrib.auth.models import User
from app_auth.models import School
from django import forms
from decimal import Decimal

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'type':'text', 'class': 'login-field', 'placeholder': 'Username', 'autofocus':'autofocus', 'autocomplete':'off'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'login-field', 'placeholder':'Password'}))

class PasswordForm(forms.Form):
	OldPassword = forms.CharField( label='Old Password', widget=forms.PasswordInput(attrs={'type':'password', 'class': 'span3', 'placeholder': 'Required', 'name': 'newPassword'}))
	password = forms.CharField( label='Password', widget=forms.PasswordInput(attrs={'type':'password', 'class': 'span3', 'placeholder': 'Required', 'name': 'newPassword'}))
	ConfPassword = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'type':'password', 'class': 'span3', 'placeholder': 'Required', 'name':'confPassword'}))

class ProfileForm(forms.Form):
	last_name = forms.CharField( label='Last Name', widget=forms.TextInput(attrs={'type':'text', 'class': 'span3', 'placeholder': 'Required', 'style':'color: #099'}))
	first_name = forms.CharField( label='First Name', widget=forms.TextInput(attrs={'type':'text', 'class': 'span3', 'placeholder': 'Required', 'style':'color: #099'}))
	username = forms.CharField( label='Username', widget=forms.TextInput(attrs={'type':'text', 'class': 'span3', 'placeholder': 'Required', 'style':'color: #099'}))
	email = forms.CharField( label='Email', widget=forms.TextInput(attrs={'type':'text', 'class': 'span3', 'placeholder': 'Required', 'style':'color: #099'}))
	street = forms.CharField( label='Street', required=False, widget=forms.TextInput(attrs={'type':'text', 'class': 'span3', 'placeholder': 'Optional'}))
	municipality = forms.CharField( label='Municipality', required=False, widget=forms.TextInput(attrs={'type':'text', 'class': 'span3', 'placeholder': 'Optional'}))
	province = forms.CharField( label='Province', required=False, widget=forms.TextInput(attrs={'type':'text', 'class': 'span3', 'placeholder': 'Optional'}))
	phone_number = forms.CharField( label='Phone Number', required=False, widget=forms.TextInput(attrs={'type':'text', 'class': 'span3', 'placeholder': 'Optional'}))
	avatar = forms.ImageField(label='Avatar', required=False, widget=forms.ClearableFileInput(attrs={'type':'file', 'class':'filestyle span3'}))

class schoolForStudent(forms.Form):
	school = forms.ModelChoiceField(label='School', queryset=School.objects.all(), widget=forms.Select(attrs={'class':'select span12', 'data-size':10, }))

class schoolForTeacher(forms.Form):
	school = forms.ModelMultipleChoiceField(label='School', queryset=School.objects.all(), widget=forms.SelectMultiple(attrs={'class':'select span12', 'data-size':10, }))

	def cleaned_school(self):
		data = self.cleaned_data.get('school', [])
		return data.split(',')

class GradeForm_Option1(forms.Form):
	grades = forms.CharField(max_length=1024, widget=forms.TextInput(attrs={'class':'tagsinput', 'style':'display: none;' }))

	def clean_grades(self):
		grades = self.cleaned_data['grades']
		num_input = len(grades.split(','))
		if num_input < 2:
			raise forms.ValidationError("Enter at least 2 grade values.")
		return grades

class GradeForm_Option2(forms.Form):
	start = forms.FloatField(widget=forms.TextInput(attrs={'class':'span1'}))
	end = forms.FloatField(widget=forms.TextInput(attrs={'class':'span1'}))
	step = forms.FloatField(widget=forms.TextInput(attrs={'class':'span1'}))

	def clean_step(self):
		clean_start = self.cleaned_data['start']
		clean_end = self.cleaned_data['end']
		clean_step = self.cleaned_data['step']

		if Decimal(str(clean_end - clean_start + 1))%Decimal(str(clean_step)) != Decimal('0.0'):
			raise forms.ValidationError("Using this interval won't reach the last possible grade value.")
		return clean_step

app_auth/views.py
try:
    from urllib.parse import urlparse
except ImportError:
    from urlparse import urlparse
   
from app_registration import signals
from django.shortcuts import render_to_response, render, redirect, get_object_or_404
from django.conf import settings
from django.core.files.uploadedfile import SimpleUploadedFile
from django.http import HttpResponse
from django.template import RequestContext
from django.db.models import Q
from django.contrib.auth import (
	REDIRECT_FIELD_NAME, login, logout, authenticate
)
from  django.contrib.auth.views import logout_then_login
from django.contrib.auth.models import User, check_password
from django.http import HttpResponseRedirect
from django.views.generic.edit import FormView
from django.core.context_processors import csrf
from app_auth.models import UserProfile, passwordForm, Student, Teacher, School
from app_classes.models import Class
from app_essays.models import Essay, EssayResponse
from app_essays.models import GradingSystem, GradeSysForm, Grade
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .forms import LoginForm, PasswordForm, ProfileForm, schoolForStudent, schoolForTeacher, GradeForm_Option1, GradeForm_Option2

import numpy

class LoginView(FormView):
	form_class = LoginForm
	redirect_field_name = REDIRECT_FIELD_NAME
	template_name = 'app_auth/login.html'
	success_url = '/dashboard'
	
	def dispatch(self, request, *args, **kwargs):
		if request.user.is_authenticated():
			return HttpResponseRedirect(self.get_success_url())
		else:
			return super(LoginView, self).dispatch(request, *args, **kwargs)
	
	def form_valid(self, form, request):
		username = form.cleaned_data['username']
		password = form.cleaned_data['password']
			
		user = authenticate(username=username, password=password)
			
		if user is not None:
			if user.is_active:
				login(self.request, user)
				return HttpResponseRedirect(self.get_success_url())			
		else:		
			return self.form_invalid(form, request)
	
	def form_invalid(self, form, request):
		return render_to_response( self.template_name , {
			'errors': 1,
			'form' : form, 
		},  RequestContext(request))
	
	def get_success_url(self):
		if self.success_url:
			redirect_to = self.success_url
		else:
			redirect_to = self.request.REQUEST.get(self.redirect_field_name, '')

		netloc = urlparse(redirect_to)[1]
		
		if not redirect_to:
			redirect_to = settings.LOGIN_REDIRECT_URL
		elif netloc and netloc != self.request.get_host():
			redirect_to = settings.LOGIN_REDIRECT_URL
		return redirect_to
	  
	def post(self, request, *args, **kwargs):
		c = {}
		c.update(csrf(request))
		form_class = self.get_form_class()
		form = self.get_form(form_class)
		
		if form.is_valid():
			return self.form_valid(form, request)
		else:				
			return self.form_invalid(form, request)

def user_logout(request):
    return logout_then_login(request,login_url='/')

@login_required(redirect_field_name='', login_url='/')
def profile_view(request):
	avatar = UserProfile.objects.get(user_id=request.user.id).avatar
	role = UserProfile.objects.get(user_id = request.user.id).role
	profile = UserProfile.objects.get(user=request.user)
	if len(Teacher.objects.filter(user_id = request.user.id)) > 0:
		role = 'Teacher'
	elif len(Student.objects.filter(user_id = request.user.id)) > 0:
		role = 'Student'
	return render(request, 'app_auth/profile_view.html', {'avatar': avatar, 'role':role, 'profile':profile, 'role':role})


@login_required(redirect_field_name='', login_url='/')
def profile_edit(request, success=None):
	user_info = UserProfile.objects.filter(user_id = request.user.id)
	power = False

	if request.method == "POST":
		formProfile = ProfileForm(request.POST, request.FILES)
		schoolForm = schoolForStudent(request.POST)
		if request.user.is_staff:
			schoolForm = schoolForTeacher(request.POST)
		power = True

		if schoolForm.is_valid():
			if request.user.is_staff:
				temp = schoolForm.cleaned_data['school']
				teacher = Teacher.objects.filter(user=request.user)
				if not teacher.exists():
					teacher = Teacher.objects.create(user=request.user)
					teacher.save()
				else:
					teacher = teacher.get(user=request.user)
					teacher.school.clear()
				for school in temp:
					print(school)
					teacher.school.add(school)
			else:
				temp = schoolForm.cleaned_data
				student = Student.objects.filter(user=request.user)
				if not student.exists():
					student = Student.objects.create(user=request.user, school=temp['school'])
		if formProfile.is_valid():
			temp = formProfile.cleaned_data
			if user_info.exists():
				#userProfile update
				userProfile_info = user_info.get(user_id=request.user.id)
				userProfile_info.avatar = userProfile_info.avatar

				if not temp['avatar']:
					userProfile_info.avatar = 'images/avatars/user.png'
				else:
					userProfile_info.avatar = temp['avatar']	
				
				userProfile_info.street = temp['street']
				userProfile_info.municipality = temp['municipality']
				userProfile_info.province = temp['province']
				userProfile_info.phone_number = temp['phone_number']
				userProfile_info.save()

			else:	
				UserProfile.objects.create(avatar=temp['avatar'], user_id=request.user.id, street=temp['street'], municipality=temp['municipality'], province=temp['province'], phone_number=temp['phone_number'])
			
			#user update
			USER_info = User.objects.get(id=request.user.id)
			USER_info.last_name = temp['last_name']
			USER_info.first_name = temp['first_name']
			USER_info.email = temp['email']
			USER_info.username = temp['username']
			USER_info.save()
			return redirect("auth:profile")
	if user_info.exists():
		schoolForm = schoolForStudent()
		user_info = user_info.get(user_id=request.user.id)
		role = UserProfile.objects.get(user_id = request.user.id).role

		if request.user.is_staff:
			schoolForm = schoolForTeacher(initial={'school':Teacher.objects.get(user=request.user).school.values_list('id',flat=True)})
		
		avatar = user_info.avatar
		if not power:
			try:
				schoolForm = schoolForStudent(initial={'school':Student.objects.get(user=request.user).school})
			except:
				pass
			if request.user.is_staff:
				schoolForm = schoolForTeacher(initial={'school':Teacher.objects.get(user=request.user).school.values_list('id',flat=True)})
			formProfile = ProfileForm(initial={
				'last_name':request.user.last_name, 'first_name':request.user.first_name, 'email':request.user.email, 'avatar':user_info.avatar,
				'username': request.user.username, 'street':user_info.street, 'municipality':user_info.municipality,
				'province': user_info.province, 'phone_number': user_info.phone_number
			})
	else:
		schoolForm = schoolForStudent()
		if request.user.is_staff:
			schoolForm = schoolForTeacher()
		avatar = 'images/avatars/user.png'
		role = None
		formProfile = ProfileForm(initial={'last_name':request.user.last_name, 'first_name':request.user.first_name, 'email':request.user.email,
			'username': request.user.username,})
	return render(request, 'app_auth/profile_edit.html', {'avatar': avatar, 'role':role, 'role':role, 'active_nav':'PROFILE', 'success':success, 'formProfile':formProfile, 'schoolForm':schoolForm})

@login_required(redirect_field_name='', login_url='/')
def password_edit(request, success=None):
	user_info = UserProfile.objects.filter(user_id = request.user.id)
	role = UserProfile.objects.get(user_id = request.user.id).role

	if not user_info.exists():
		return redirect("/profile")
	user_info = user_info.get(user_id = request.user.id)
	avatar = user_info.avatar
	err = None
	power = False
	if request.user.is_staff:
		power = True
	if request.method == "POST":
		form_class = PasswordForm(data=request.POST)
		if form_class.is_valid():
			forms = form_class.cleaned_data
			password = forms['password']
			newPassword = forms['ConfPassword']
			oldPassword = forms['OldPassword']
			u = User.objects.get(id=request.user.id)

			if u.check_password(oldPassword) and password == newPassword:
				u.set_password(newPassword)
				u.save()
				success = 'You have changed your password.'
			else:
				err = 'Passwords did not matched.'
	else:
		form_class = PasswordForm()

	return render(request, 'app_auth/changePassword.html', {'avatar': avatar, 'role':role, 'active_nav':'ACCOUNT', 'power':power,'user_info':user_info, 'form':form_class, 'error': err, 'success':success})

@login_required(redirect_field_name='', login_url='/')
def grading_system(request):
	avatar = UserProfile.objects.get(user_id=request.user.id).avatar
	role = UserProfile.objects.get(user_id = request.user.id).role

	gradingsys = GradingSystem.objects.filter(created_by=request.user, is_active=1)
	gradingsys_admin = GradingSystem.objects.filter(created_by=1, is_active=1)

	return render(request, 'app_auth/grading_systems.html', {'avatar': avatar, 'role':role, 'active_nav':'GRADESYS', 'gradingsys':gradingsys, 'gradingsys_admin':gradingsys_admin})

@login_required(redirect_field_name='', login_url='/')
def grading_system_view(request, gradeSys_id):
	gradesys = get_object_or_404(GradingSystem, Q(created_by__pk=1) | Q(created_by=request.user), pk=gradeSys_id, is_active=1)
	grades = Grade.objects.filter(grading_system=gradesys).order_by('value')
	by_admin = 1 if gradesys.created_by.pk == 1 else 0
	return render(request, 'app_auth/grading_systems_view.html', {'gradesys': gradesys, 'grades': grades, 'by_admin':by_admin})

@login_required(redirect_field_name='', login_url='/')
def grading_system_new(request):
	avatar = UserProfile.objects.get(user_id=request.user.id).avatar
	role = UserProfile.objects.get(user_id = request.user.id).role
	
	if request.method == 'POST':
		formSys = GradeSysForm(request.POST, request)
		if 'option1' in request.POST:

templates/app_auth/changePassword.html
{% extends "base/base_settings.html" %}
{% load staticfiles %}

{% block title %}
TECS: Test Essay Checking Software | Teacher Classes
{% endblock %}

{% block content %}
<div class="page-content">
	<div class="row-fluid">
		<div class="span11 content">
			<img class="title-icons" src="{% static 'base/img/icons/password_manager.png' %}">
			<h3 class="title">Change Password</h3>

			{% if error %}
				<div class="alert alert-block alert-error">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
						<h4><strong>Oops!</strong></h4> {{ error }}
				</div>
			{% endif %}
			{% if success %}
				<div class="alert alert-block alert-success">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
						<h4><strong>Success!</strong></h4> {{ success }}
				</div>
			{% endif %}

			<section>
				<form class="form-horizontal" action="{% url 'auth:edit_password' %}" method="post">	{% csrf_token %}
					<fieldset>	
						{% for forms in form %}
						<div class="control-group">
							<label class="control-label" for="newPassword">{{ forms.label_tag }}</label>
							<div class="controls">
								{{ forms }}
								{% for error in forms.errors %}
								<p class="text-error">{{ error }}</p>
								{% endfor %}
							</div>	
						</div> 
						{% endfor %}
						<div class="form-actions">	
							<button type="submit" class="btn btn-primary"><b>Update Password</b> <i class="fui-lock"></i></button> 
							<button type="reset" class="btn btn-warning"><b>Reset</b> <i class="fui-play"></i></button>	 
						</div>	 	
					</fieldset>
				</form> 
			</section>
		</div>
	</div>
</div>


{% endblock content %}

templates/app_auth/grading_systems.html
{% extends "base/base_settings.html" %}
{% load staticfiles %}

{% block title %}
TECS: Test Essay Checking Software | Settings
{% endblock %}

{% block content %}
<div class="page-content">
	<div class="row-fluid">
		<div class="content">				
			<p class="pull-right">
				<a href="{% url 'auth:gradesys_new' %}" class="btn btn-primary"><i class="fui-plus"></i><strong> Create Custom Grading System</strong></a>
			</p>
			
			<img class="title-icons" src="{% static 'base/img/icons/Trophy.png' %}">		
			<h3 class="title">Grading Systems</h3>
			<div class="span8">
				{% if gradingsys.count > 0 %}					
					<div class="palette palette-carrot">
						<strong>Custom Grading Systems</strong>
					</div>
					<table class="table table-striped">
						<thead>
							<tr>
								<th style="width: 10%"><center>#</center></th>
								<th style="width: 36%"><center>Name</center></th>
								<th style="width: 36%"><center>Description</center></th>
								<th style="width: 7%"><center>View</center></th>
								<th style="width: 7%"><center>Delete</center></th>
							</tr>
						</thead>
						<tbody>
							{% for gradeSys in gradingsys %}
								<tr>
									<td><center>{{forloop.counter}}</center></td>
									<td><center>{{gradeSys.system}}</center></td>
									<td><center>{{gradeSys.description}}</center></td>
									<td><center><a href="{% url 'auth:grades' gradeSys.id %}" class="view-gradesys btn btn-primary"><span class=""><i class="fui-eye"></i></span></a></center></td>
									<td><center><button type="button" class="delsys-button btn btn-danger" data-id={{ gradeSys.id }} data-toggle="modal" data-target="#confirm-delete"><i class="fui-cross"></i></span></button></center></td>
								</tr>
							{% endfor %}
						</tbody> 
					</table>
				{% endif %}

				{% if gradingsys_admin.count > 0 %}
					<div class="palette palette-sun-flower">
						<strong>Preset Grading Systems</strong>
					</div>
					<table class="table table-striped">
						<thead>
							<tr>
								<th style="width: 10%"><center>#</center></th>
								<th style="width: 36%"><center>Name</center></th>
								<th style="width: 36%"><center>Description</center></th>
								<th style="width: 14%"><center>View</center></th>
							</tr>
						</thead>
						<tbody>
							{% for gradeSys in gradingsys_admin %}
								<tr>
									<td><center>{{ forloop.counter }}</center></td>
									<td><center>{{gradeSys.system}}</center></td>
									<td><center>{{gradeSys.description}}</center></td>
									<td><center><a href="{% url 'auth:grades' gradeSys.id %}" class="delsys-button view-gradesys btn btn-primary"><span class=""><i class="fui-eye"></i></span></a></center></td>
								</tr>
							{% endfor %}
						</tbody> 
					</table>
				{% endif %}
			</div>
			<div class="span4 ">
				<div class="palette palette-midnight-blue mls">
					<strong>VIEW DETAILS</strong>
				</div>
				<div id="gradesys-view" class="mll mtl mrs">
				</div>		
			</div>
		</div>
	</div>
</div>

<div id="confirm-delete" class="modal hide fade" data-backdrop="static">
	<div class="modal-header palette-alizarin">
		<h3 class="text-white">Confirm Delete</h3>
	</div>
	<div class="modal-body">
		<p>Are you sure you want to delete this grading system?</p>
		<p>Continuing with this action, however, does not affect any previous exams that used this system. </p>
		<form action="{% url 'auth:gradesys_delete' %}" method="post">
			{% csrf_token %}
			<input type="hidden" id="gradesysid" name="gradesysid" value="">
		<form>
	</div>
	<div class="modal-footer">
		<button type="submit" name="gradesys-delete" class="btn btn-danger pull-left">Delete <span class="fui-cross"></span></button>
		<button class="btn btn-inverse" data-dismiss="modal" aria-hidden="true">Close</button>
	</div>
</div>

<script>
	$(function() {
		$('.view-gradesys').click( function() {
        	$.get( $(this).attr('href'), function(data) {
        		$("#gradesys-view").html(data);
        	});
       		return false;
		});
	});

	$(".delsys-button").on("click", function() {
		var gradesys_id = $(this).data('id')
		$("#gradesysid").val(gradesys_id)
	});
</script>

{% endblock content %}


{% block custom_script %}
	<script src="{% static 'base/js/flatui-checkbox.js' %}"></script>
{% endblock %}

templates/app_auth/grading_systems_view.html
{% if by_admin == 1 %}
	<span class="label label-info pull-right">PRESET</span>
{% endif %}
<h4 class="mbm"><strong>{{ gradesys.system }}</strong></h4>
<p>{{ gradesys.description }}</p>					
<p class="palette-paragraph muted">from highest to lowest</p>
{% for grade in grades %}
	<span class="palette palette-green-sea pull-left mrs mbs">{{ grade.name }}</span>
{% endfor %}

templates/app_auth/student_dashboard.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block title %}
TECS: Test Essay Checking Software | Home
{% endblock %}

{% block content %}
<div class="page-content">
	<div class="content">
		<img class="title-icons" src="{% static 'base/img/icons/Dashboard.png' %}">
		<h3>Dashboard</h3>
		<hr>
		<div class="hero-unit">
			<h1>Hello, {{ request.user.first_name }}</h1>
			<p>Welcome to TECS: Test Essay Checking Software.</p>
			
			<div class="row-fluid demo-tiles login-screen">
				<div class="row-fluid">				
					<div class="span4"><a href="{% url 'classes:classes' %}" style="text-decoration:none">
						<div class="tile">
							<img src="{% static 'base/img/icons/chalkboard-icon.png' %}"  class="tile-image big-illustration">
							<h3 class="tile-title">My Classes</h3>
							<div class="palette {% if not class_count %}palette-alizarin{% else %}palette-emerald{% endif %}"><h3>{{ class_count }}</h3></div>
						<a></div>
					</div>

					<div class="span4"><a href="{% url 'essays:list' %}" style="text-decoration:none">
						<div class="tile">
							<img src="{% static 'base/img/icons/pencil.png' %}" class="tile-image big-illustration">
							<h3 class="tile-title">New Exams</h3>
							<div class="palette {% if in_progress_count %}palette-alizarin{% else %}palette-emerald{% endif %}"><h3>{{ exam_count }}</h3></div>
						</a></div>
					</div>

					<div class="span4"><a href="{% url 'essays:list' %}" style="text-decoration:none">
					 	<div class="tile">
							<img src="{% static 'base/img/icons/Pensils@2x.png' %}"  class="tile-image big-illustration">
							<h3 class="tile-title">Exams In-Progress</h3>
						 <div class="palette {% if in_progress_count %}palette-alizarin{% else %}palette-emerald{% endif %}"><h3>{{ in_progress_count }}</h3></div>
						</a></div>
					</div>
				</div>
			 </div>
		</div>
	</div>
</div>
{% endblock %}



templates/app_auth/teacher_dashboard.html
{% extends "base/base.html" %}
{% load staticfiles %}

{% block title %}
TECS: Test Essay Checking Software | Home
{% endblock %}

{% block content %}
<div class="page-content">
	<div class="content">
		<img class="title-icons" src="{% static 'base/img/icons/Dashboard.png' %}">
		<h3>Dashboard</h3>
		<hr>
		<div class="hero-unit">
			<h1>Hello, {{ request.user.first_name }}</h1>
			<p>Welcome to TECS: Test Essay Checking Software.</p>
			
			<div class="row-fluid demo-tiles login-screen">
				<div class="row-fluid">				
					<div class="span4"><a href="{% url 'classes:classes' %}" style="text-decoration:none">
						<div class="tile">
							<img src="{% static 'base/img/icons/chalkboard-icon.png' %}"  class="tile-image big-illustration">
							<h3 class="tile-title">My Classes</h3>
							<div class="palette {% if not class_count %}palette-alizarin{% else %}palette-emerald{% endif %}"><h3>{{ class_count }}</h3></div>
						</a></div>
					</div>

					<div class="span4">
						<div class="tile"><a href="{% url 'essays:list' %}" style="text-decoration:none">
							<img src="{% static 'base/img/icons/Pensils@2x.png' %}" class="tile-image big-illustration">
							<h3 class="tile-title">Ongoing-Exams</h3>
							<div class="palette palette-emerald"><h3>{{ exam_count }}</h3></div>
						</a></div>
					</div>

					<div class="span4">
					 	<div class="tile"><a href="{% url 'essays:list' %}" style="text-decoration:none">
							<img src="{% static 'base/img/icons/Retina-Ready@2x.png' %}"  class="tile-image big-illustration">
							<h3 class="tile-title">Needs Grading</h3>
						 <div class="palette {% if needs_grading_count %}palette-alizarin{% else %}palette-emerald{% endif %}"><h3>{{ needs_grading_count }}</h3></div>
						</a></div>
					</div>
				</div>
			 </div>
		</div>
	</div>


</div>
{% endblock %}

